spring:
  application:
    name: zorvyn-finance

  # Default profile: PostgreSQL
  datasource:
    url: jdbc:postgresql://localhost:5432/zorvyn_finance
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false

server:
  port: ${PORT:8080}

app:
  jwt:
    secret: ${JWT_SECRET:zorvyn-finance-jwt-secret-key-for-development-only-change-in-production-min-256-bits-long}
    expiration-ms: ${JWT_EXPIRATION:86400000}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: method
